# this environment follow https://www.tensorflow.org/install/pip
name: p3u

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1
  - pip
  - pip:
    - -r requirements.txt