dataset_name: all
model_name: pos_only
train_entropy: all
savedir: saved
init_window: 30
m_window: 5
h_window: 25
gpu_id: 0
train_size: 0.8
test_size: 0.2
epochs: 30
batch_size: 128
lr: 0.0005
wandb_mode: online
minsize: False
hydra:
  run: # https://hydra.cc/docs/configure_hydra/workdir/
    dir: '/tmp/'
  job: # https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/
    chdir: False
  help: # https://hydra.cc/docs/0.11/configure_hydra/app_help/
    app_name: predict360user.trainer
    template: |-
      ${hydra.help.app_name} module train and evaluate models to predict user behaviour in 360 videos.

      It uses a hydra powered cli. Use --hydra-help to view Hydra specific help.
      See below its default config. You can override everything, for example dataset_name=david
      -------
      $CONFIG-------
  job_logging: # https://hydra.cc/docs/configure_hydra/logging/
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    root:
      handlers: [console]